var unusedDeck = []; // Populates on init

const majorArcana = [
    "the_fool",
    "the_magician",
    "the_high_priestess",
    "the_empress",
    "the_emperor",
    "the_hierophant",
    "the_lovers",
    "the_chariot",
    "strength",
    "the_hermit",
    "wheel_of_fortune",
    "justice",
    "the_hanged_man",
    "death",
    "temperance",
    "the_devil",
    "the_tower",
    "the_star",
    "the_moon",
    "the_sun",
    "judgement",
    "the_world"
];

const tarotDeck = [
    // Major Arcana
    { id: "the_fool", name: "The Fool", sx: 0, sy: 0 },
    { id: "the_magician", name: "The Magician", sx: 1, sy: 0 },
    { id: "the_high_priestess", name: "The High Priestess", sx: 2, sy: 0 },
    { id: "the_empress", name: "The Empress", sx: 3, sy: 0 },
    { id: "the_emperor", name: "The Emperor", sx: 4, sy: 0 },
    { id: "the_hierophant", name: "The Hierophant", sx: 5, sy: 0 },
    { id: "the_lovers", name: "The Lovers", sx: 6, sy: 0 },
    { id: "the_chariot", name: "The Chariot", sx: 7, sy: 0 },
    { id: "strength", name: "Strength", sx: 0, sy: 1 },
    { id: "the_hermit", name: "The Hermit", sx: 1, sy: 1 },
    { id: "wheel_of_fortune", name: "Wheel of Fortune", sx: 2, sy: 1 },
    { id: "justice", name: "Justice", sx: 3, sy: 1 },
    { id: "the_hanged_man", name: "The Hanged Man", sx: 4, sy: 1 },
    { id: "death", name: "Death", sx: 5, sy: 1 },
    { id: "temperance", name: "Temperance", sx: 6, sy: 1 },
    { id: "the_devil", name: "The Devil", sx: 7, sy: 1 },
    { id: "the_tower", name: "The Tower", sx: 0, sy: 2 },
    { id: "the_star", name: "The Star", sx: 1, sy: 2 },
    { id: "the_moon", name: "The Moon", sx: 2, sy: 2 },
    { id: "the_sun", name: "The Sun", sx: 3, sy: 2 },
    { id: "judgement", name: "Judgement", sx: 4, sy: 2 },
    { id: "the_world", name: "The World", sx: 5, sy: 2 },

    // Minor Arcana - Wands
    { id: "ace_of_wands", name: "Ace of Wands", sx: 0, sy: 3 },
    { id: "two_of_wands", name: "Two of Wands", sx: 1, sy: 3 },
    { id: "three_of_wands", name: "Three of Wands", sx: 2, sy: 3 },
    { id: "four_of_wands", name: "Four of Wands", sx: 3, sy: 3 },
    { id: "five_of_wands", name: "Five of Wands", sx: 4, sy: 3 },
    { id: "six_of_wands", name: "Six of Wands", sx: 5, sy: 3 },
    { id: "seven_of_wands", name: "Seven of Wands", sx: 6, sy: 3 },
    { id: "eight_of_wands", name: "Eight of Wands", sx: 7, sy: 3 },
    { id: "nine_of_wands", name: "Nine of Wands", sx: 0, sy: 4 },
    { id: "ten_of_wands", name: "Ten of Wands", sx: 1, sy: 4 },
    { id: "page_of_wands", name: "Page of Wands", sx: 2, sy: 4 },
    { id: "knight_of_wands", name: "Knight of Wands", sx: 3, sy: 4 },
    { id: "queen_of_wands", name: "Queen of Wands", sx: 4, sy: 4 },
    { id: "king_of_wands", name: "King of Wands", sx: 5, sy: 4 },

    // Minor Arcana - Cups
    { id: "ace_of_cups", name: "Ace of Cups", sx: 6, sy: 4 },
    { id: "two_of_cups", name: "Two of Cups", sx: 7, sy: 4 },
    { id: "three_of_cups", name: "Three of Cups", sx: 0, sy: 5 },
    { id: "four_of_cups", name: "Four of Cups", sx: 1, sy: 5 },
    { id: "five_of_cups", name: "Five of Cups", sx: 2, sy: 5 },
    { id: "six_of_cups", name: "Six of Cups", sx: 3, sy: 5 },
    { id: "seven_of_cups", name: "Seven of Cups", sx: 4, sy: 5 },
    { id: "eight_of_cups", name: "Eight of Cups", sx: 5, sy: 5 },
    { id: "nine_of_cups", name: "Nine of Cups", sx: 6, sy: 5 },
    { id: "ten_of_cups", name: "Ten of Cups", sx: 7, sy: 5 },
    { id: "page_of_cups", name: "Page of Cups", sx: 0, sy: 6 },
    { id: "knight_of_cups", name: "Knight of Cups", sx: 1, sy: 6 },
    { id: "queen_of_cups", name: "Queen of Cups", sx: 2, sy: 6 },
    { id: "king_of_cups", name: "King of Cups", sx: 3, sy: 6 },

    // Minor Arcana - Swords
    { id: "ace_of_swords", name: "Ace of Swords", sx: 4, sy: 6 },
    { id: "two_of_swords", name: "Two of Swords", sx: 5, sy: 6 },
    { id: "three_of_swords", name: "Three of Swords", sx: 6, sy: 6 },
    { id: "four_of_swords", name: "Four of Swords", sx: 7, sy: 6 },
    { id: "five_of_swords", name: "Five of Swords", sx: 0, sy: 7 },
    { id: "six_of_swords", name: "Six of Swords", sx: 1, sy: 7 },
    { id: "seven_of_swords", name: "Seven of Swords", sx: 2, sy: 7 },
    { id: "eight_of_swords", name: "Eight of Swords", sx: 3, sy: 7 },
    { id: "nine_of_swords", name: "Nine of Swords", sx: 4, sy: 7 },
    { id: "ten_of_swords", name: "Ten of Swords", sx: 5, sy: 7 },
    { id: "page_of_swords", name: "Page of Swords", sx: 6, sy: 7 },
    { id: "knight_of_swords", name: "Knight of Swords", sx: 7, sy: 7 },
    { id: "queen_of_swords", name: "Queen of Swords", sx: 0, sy: 8 },
    { id: "king_of_swords", name: "King of Swords", sx: 1, sy: 8 },

    // Minor Arcana - Pentacles
    { id: "ace_of_pentacles", name: "Ace of Pentacles", sx: 2, sy: 8 },
    { id: "two_of_pentacles", name: "Two of Pentacles", sx: 3, sy: 8 },
    { id: "three_of_pentacles", name: "Three of Pentacles", sx: 4, sy: 8 },
    { id: "four_of_pentacles", name: "Four of Pentacles", sx: 5, sy: 8 },
    { id: "five_of_pentacles", name: "Five of Pentacles", sx: 6, sy: 8 },
    { id: "six_of_pentacles", name: "Six of Pentacles", sx: 7, sy: 8 },
    { id: "seven_of_pentacles", name: "Seven of Pentacles", sx: 0, sy: 9 },
    { id: "eight_of_pentacles", name: "Eight of Pentacles", sx: 1, sy: 9 },
    { id: "nine_of_pentacles", name: "Nine of Pentacles", sx: 2, sy: 9 },
    { id: "ten_of_pentacles", name: "Ten of Pentacles", sx: 3, sy: 9 },
    { id: "page_of_pentacles", name: "Page of Pentacles", sx: 4, sy: 9 },
    { id: "knight_of_pentacles", name: "Knight of Pentacles", sx: 5, sy: 9 },
    { id: "queen_of_pentacles", name: "Queen of Pentacles", sx: 6, sy: 9 },
    { id: "king_of_pentacles", name: "King of Pentacles", sx: 7, sy: 9 },
];
