const treeData = {
    "danger": ["yourself", "look", "armchair", "up"],
    "yourself": ["jacket", "pants", "magazine"],
    "jacket": ["plaid", "pocket"],
    "pants": ["jellybeans"],
    "magazine": ["fishing"],
    "armchair": ["faded", "remote", "pillow"],
    "pillow": ["letter"],
    "letter": ["inheritance"],
    "inheritance": ["logcabin"],
    "look": ["television", "fireplace"],
    "television": ["on"],
    "on": ["newsreport"],
    "newsreport": ["escapee"],
    "fireplace": ["coal", "embers", "log"],
    "embers": ["ouch"],
    "log": ["newspaper"],
    "newspaper": ["typhoon"],
    "up": ["window", "kitchen", "hallway"],
    "window": ["dark", "raining", "cobweb", "dirty", "someone?", "trees"],
    "dirty": ["blurry"],
    "trees": ["shaking"],
    "cobweb": ["hole"],
    "hole": ["spider"],
    "spider": ["spiderbabies"],
    "kitchen": ["table", "counter", "fridge"],
    "fridge": ["cold", "raw meat"],
    "cold": ["shudder"],
    "table": ["keychain", "frontpage", "stamps", "note"],
    "keychain": ["lock"],
    "lock": ["beep"],
    "frontpage": ["jailbreak"],
    "note": ["handwritten", "holiday"],
    "holiday": ["enjoy!"],
    "counter": ["envelopes", "microwave", "phone"],
    "phone": ["disconnected"],
    "microwave": ["press"],
    "press": ["mac"],
    "mac": ["cheese"],
    "hallway": ["bathroom", "bedroom", "door"],
    "bathroom": ["casement", "toilet"],
    "casement": ["latch"],
    "latch": ["rain", "darkness", "whistle"],
    "toilet": ["tank", "seat"],
    "seat": ["use"],
    "use": ["relief"],
    "tank": ["greywater", "package"],
    "package": ["passport", "id", "money", "cigarettes"],
    "passport": ["mr. leeds"],
    "id": ["john", "196cm", "119kg"],
    "bedroom": ["closet", "bed", "desk"],
    "closet": ["vintage", "trenchcoat", "shoebox"],
    "shoebox": ["photos", "clippings"],
    "bed": ["duvet", "under"],
    "under": ["floorboards"],
    "floorboards": ["loose"],
    "loose": ["safe"],
    "safe": ["locked"],
    "desk": ["mug", "laptop", "tiny"],
    "tiny": ["initials"],
    "initials": ["jml"],
    "laptop": ["browser"],
    "browser": ["offline"],
    "door": ["knocking"],
    "knocking": ["unlock"],
    "unlock": ["thunderstorm", "blackness", "wind", "forest", "steps"],
    "steps": ["mat"],
    "mat": ["paper"],
    "paper": ["you're in my house"]
}